name: 'Update Flake Inputs'
description: 'Creates pull requests for each flake input update'
author: 'Your Name'

inputs:
  github-token:
    description: 'GitHub token for creating pull requests'
    required: true
  exclude-patterns:
    description: 'Comma-separated list of glob patterns to exclude flake.nix files'
    required: false
    default: ''

runs:
  using: 'node20'
  main: 'dist/index.js'
